version: '3.8'
services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:8.2
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.2
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data: