version: '3.8'
services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:8.2
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.2
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth_service:
    build: .
    command: python3 -m services.auth.server
    ports:
      - "50051:50051"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  presence_service:
    build: .
    command: python3 -m services.presence.server
    ports:
      - "50053:50053"
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq

volumes:
  postgres_data: